### ISSUE TITLE
Add support for DECRQM

### ISSUE THREAD

**Issue by kchibisov** [alacritty/vte#100]
It's used to report whether mode is supported/set, etc.

This is used by sync updates as a way to detect the feature support. See https://gist.github.com/christianparpart/d8a62cc1ab659194337d73e399004036?permalink_comment_id=3946967#feature-detection

The mode could still be used without it, but it probably worth adding support for this escape in general.

**Comment by gpanders** [comment]
We are adding support for [synchronized updates to Neovim](https://github.com/neovim/neovim/pull/25871) and rely on DECRQM to determine support from the host terminal. We explicitly _do not_ use the `Sync` terminfo entry because many terminals (Alacritty included) still use the old DCS sequence, which we have chosen not to support.

All that is to say that supporting DECRQM in Alacritty will bring this feature to your users as well.

**Comment by kchibisov** [comment]
@gpanders alacritty supports sync updates.

**Comment by kchibisov** [comment]
Ah, you rely on it to be present. But you can't detect DCS with DECRQM, because DECRQM is a part of CSI and for CSI modes, no?

**Comment by gpanders** [comment]
> @gpanders alacritty supports sync updates.

Right, but we query for support using DECRQM first. We could just unconditionally send the DECSET and DECRST sequences to toggle the 2026 mode and count on terminal emulators ignoring sequences they don't support, but we are trying to be a well behaved application by actually asking the terminal what it supports and only sending the sequence if it is.

>But you can't detect DCS with DECRQM, because DECRQM is a part of CSI and for CSI modes, no?

Correct, we can't detect DCS with DECRQM which is part of the reason we don't support the older DCS sequence at all. We _could_ detect `Sync` support via terminfo and support both the DCS and DECSET versions of synchronized updates, but the issue there is that both sequences use different parameters for enabling/disabling (1 and 2 for DCS, 1 and 0 for DECSET). Instead of dealing with that complexity, we only use mode 2026 (since every terminal emulator that supports synchronized updates also supports mode 2026, and the DCS sequence is unofficially deprecated anyway).
